<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-GRUJ0M8" failures="1" tests="4" name="Test" time="24.466" errors="0" timestamp="2025-05-24T09:31:14 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="6.137"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="5.101">
    <failure type="java.lang.AssertionError" message="expected [User does not exis] but found [User does not exist.]">
      <![CDATA[java.lang.AssertionError: expected [User does not exis] but found [User does not exist.]
at steps.StepDefination.alert_message_with_error_should_be_shown_to_the_user(StepDefination.java:63)
at âœ½.Alert message with error should be shown to the user(file:///D:/edureka17/workspace/seleniumbddmvnproject/features/Login.feature:20)
... Removed 6 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="5.302"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="7.135"/>
</testsuite> <!-- Test -->
