<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-GRUJ0M8" failures="1" tests="4" name="Default test" time="23.02" errors="0" timestamp="2025-05-24T09:26:29 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="5.609"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="5.773">
    <failure type="java.lang.AssertionError" message="expected [User does not exis] but found [User does not exist.]">
      <![CDATA[java.lang.AssertionError: expected [User does not exis] but found [User does not exist.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at steps.StepDefination.alert_message_with_error_should_be_shown_to_the_user(StepDefination.java:63)
at âœ½.Alert message with error should be shown to the user(file:///D:/edureka17/workspace/seleniumbddmvnproject/features/Login.feature:20)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="5.019"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="5.856"/>
</testsuite> <!-- Default test -->
